name: Freezer
version: 1.0.1
main: RTG\Freeze\FreezeEm
api: [3.0.0-ALPHA11]
author: VMPE Development Team
commands:
  freeze:
    usage: "/freeze"
    permission: freeze.player
    description: "Freezes a Player!"
  unfreeze:
    usage: "/unfreeze"
    permission: unfreeze.player
    description: "Unfreezes a Player!"
permissions:
  freeze.player:
    default: op
  unfreeze.player:
    default: op
